# Generated by Django 2.0.5 on 2018-05-20 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image_url',
            new_name='image',
        ),
    ]
