# Generated by Django 2.0.5 on 2018-05-16 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='request_hook',
        ),
    ]
